### ISSUE TITLE
Bug with new conditional-compile

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/bslint#113]
Looks like there's a bug with bslint with the new conditional compile AST structure in bslint `1.0.0-alpha.33`? 

![image](https://github.com/rokucommunity/bslint/assets/2544493/d4dc4924-a761-45f4-9ce3-767d01ec048c)

**Comment by markwpearce** [comment]
Yep… looks like an issue with the new conditional compilation stuff
