### ISSUE TITLE
Properly handle TypeCastExpression in v1

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/bslint#117]
bslint is treating typecast expressions like grouping expressions and validating the types as if they were runtime variables. We shouldn't do that. 

Also, do we even need LINT1001 anymore with how rhobust v1 is?

![image](https://github.com/user-attachments/assets/b2ba33b2-4fe5-405c-a8fa-48dfaf97add9)

**Comment by markwpearce** [comment]
closed with #122
