### ISSUE TITLE
Functions declared in other source files not found. (bug)

### ISSUE THREAD

**Issue by bogdanterzea** [rokucommunity/bslint#38]
## Description
In a sceneGraph application (brightscript) I tried to use the following bsconfig file `-img1-` and after I run `npx bslint` I get the following errors `-img2-`.
![image](https://user-images.githubusercontent.com/49044962/132187908-5b3116ae-9222-4c80-b660-50e9690a68ed.png)
![image](https://user-images.githubusercontent.com/49044962/132189176-c34e3fdb-386e-4713-93df-34303de59d22.png)

### Mention:
- the `.brs` files are in the same directory and the functions should be shared between them.

**Comment by elsassph** [comment]
@TwitchBronBron the issue is apparently in `brighterscript`: I could reproduce that, when the root folder is `src/main`, for `source` scope, linter is receiving only global callables but none of the userland callables.

**Comment by elsassph** [comment]
I must close the bug here as it's a `brighterscript` bug.
