### ISSUE TITLE
Rule: newline required at end of file

### ISSUE THREAD

**Issue by elsassph** [rokucommunity/bslint#41]
A classic linting rule.

Each BrsFile has a `parser.tokens` collection where a final newline can be verified.

Should end up looking something similar to the eslint message:

![image](https://github.com/rokucommunity/bslint/assets/2544493/e5458612-4667-4a03-a1af-21f7c6536a3e)

**Comment by max-curzi** [comment]
This looks like it is implemented by LINT3017:

![image](https://github.com/user-attachments/assets/cc1b88ce-b415-481f-8a56-f9f7c199b2a6)

It's controlled by bslint.json `"rules"`:`"eol-last"`

**Comment by TwitchBronBron** [comment]
Oh yeah. You're right! Thanks. I'll close this.
