### ISSUE TITLE
Prevent usage of TODO comments

### ISSUE THREAD

**Issue by arturocuya** [rokucommunity/bslint#54]
Add following code style rules:

* `no-todo`: prevent usage of TODO comments in code (error | warn | info | off).
* `todo-pattern`: RegEx pattern to detect a TODO. Default: `TODO|todo|FIXME`

**Comment by TwitchBronBron** [comment]
We can merge `todo-keywords` and `todo-pattern` in favor of just having `todo-pattern`. It's easy enough to have people write `"TODO|todo|FIXME"`, especially if it's documented that way.

**Comment by arturocuya** [comment]
@TwitchBronBron I'm implementing this. Is there a meaning behind the error codes for code style (`CodeStyleError` enum)? Why do they start with `30`?

**Comment by TwitchBronBron** [comment]
Was this resolved by #56 ?
