### ISSUE TITLE
disallow keywords

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/bslint#6]
I put annotations in my code for rooibos, like
'@Only
'@Ignore

would be awesome to have a rule where I could say - warn if ANY of these key-words are in the code.

**Comment by elsassph** [comment]
Can you provide a more detailed example?

**Comment by TwitchBronBron** [comment]
@georgejecook this feels a little too specific to your rooibos project. you're defining a custom comment-based annotation `'@someAnnotation`. I think you should consider writing your own brighterscript plugin to catch those, as I don't see many other people benefiting from a rule like this.

**Comment by georgejecook** [comment]
well, the idea would be for any particular words, not just '@only.. maybe a grep of cuss words?..

**Comment by georgejecook** [comment]
you guys dont' want a details list of rude words, do you? :P

**Comment by elsassph** [comment]
As I said, I'd like a more detailed description of the feature. What is the goal? Is an annotation the best syntax for it? Etc. Maybe it indeed would be a legitimate lint rule, or best handled as a separate plugin.

**Comment by georgejecook** [comment]
I'll write something up tonight.

**Comment by georgejecook** [comment]
on second thoughts, @TwitchBronBron is probably right.. a generic - "report an error if this word is in the code" is not a good idea. I can write a custom plugin that does the same thing.
