### ISSUE TITLE
throw should be considered for "Not all code paths return a value"

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/bslint#71]
We consider `throw` statements as `return` statements when considering "not all code paths return a value" check. 

![image](https://user-images.githubusercontent.com/2544493/178014260-b8de4da7-d162-493b-bb9e-8025851cd5c5.png)

**Comment by georgejecook** [comment]
What's needed to fix this? I'll do it. I'm tired of faux returns to counter this.. ugly.

**Comment by elsassph** [comment]
It should be fixed since https://github.com/rokucommunity/bslint/pull/78 but maybe it wasn't released?

**Comment by TwitchBronBron** [comment]
Yeah, this has been fixed in a recent release.
