### ISSUE TITLE
spurius "error BSLINT2004: Not all code paths return a value"

### ISSUE THREAD

**Issue by ZeeD** [rokucommunity/bslint#76]
minimal test:
```brightscript
function foo() as Integer
    throw "error"
end function
```

running `bslint` on this snippet will return the error message `error BSLINT2004: Not all code paths return a value`, but IMHO this is a false result, as all branches here return (or, in this case throw) some value.

For instance I have the same error even on little variations, like

```brightscript
function foo1(bar as Boolean) as Integer
    if bar then return 42
    throw "error"
end function
```

but not on a (conceptually equals) variant, like

```brightscript
function foo2(bar as Boolean) as Integer
    if not bar then  throw "error"
    return 42
end function
```

**Comment by TwitchBronBron** [comment]
Closing as this is already being tracked by #71 . But yes, this is definitely something we need to fix at some point. I'd be happy to help you set up the bslint project to fix the bug if you're interested (I'm swamped with other work so this is a bit lower of a priority).

**Comment by ZeeD** [comment]
(oh, sorry for the duplicate, I searched with the error code and totally missed the other issue with the same error message)

**Comment by TwitchBronBron** [comment]
> (oh, sorry for the duplicate, I searched with the error code and totally missed the other issue with the same error message)

No worries!
