### ISSUE TITLE
Add explicit rule for uninitialized variables

### ISSUE THREAD

**Issue by josephjunker** [rokucommunity/bslint#79]
Our team is seeing this error while running bslint:
```
error BSLINT1001: Using uninitialised variable 'isSecondaryTemplate' when this file is included in scope 'components/core/Pages/BasePage.xml'
```
This is for a situation that should 100% be an error for a production deploy, because it will always cause a crash if this code is executed, but our current situation involves porting a project between repositories piecemeal and these errors are occurring in what's temporarily dead code. It would be nice to have this be an explicit rule that could be disabled or set to a `warn` severity.

**Comment by TwitchBronBron** [comment]
You can ignore that rule on a per-line basis by adding `bs:disable-next-line above the lines in question. Would that help your issue temporarily?

![lint-disable](https://user-images.githubusercontent.com/2544493/213866433-fd2cf04d-f4ab-4bba-9351-d3cc930e5caa.gif)
