### ISSUE TITLE
Ignore roku_modules

### ISSUE THREAD

**Issue by iBicha** [rokucommunity/bslint#81]
I'm trying to get the linter to ignore modules, but I don't seem to get it
<img width="804" alt="Screen Shot 2022-11-08 at 9 14 10 AM" src="https://user-images.githubusercontent.com/17722782/200587577-be57e1e3-5969-4acf-a984-dff7e736fc68.png">

**Comment by TwitchBronBron** [comment]
`brs1107` is a brighterscript diagnostic, so the bslint "ignores" won't work. You'll need to also add that folder to the list of diagnosticFilters in bsconfigjson
```jsonc
{
    "diagnosticFilters": [
        "components/roku_modules/**/*"
    ]
}
```

**Comment by iBicha** [comment]
Thank you!
