### ISSUE TITLE
bslint doesn't support const

### ISSUE THREAD

**Issue by ZeeD** [rokucommunity/bslint#82]
brighterscript support the definition of [constants](https://github.com/rokucommunity/brighterscript/blob/master/docs/constants.md) but it seems to me that bslint doesn't support them.
with a simple file like
```brs
const MYCONST = "..."
sub mysub()
    ? MYCONST
end sub
```
`bslint` yields `error BSLINT1001: Using uninitialised variable 'MYCONST' when this file is included in scope 'source'`.

**Comment by taschmidt** [comment]
@TwitchBronBron I'm running into this as well. Any issues with doing this?

https://github.com/taschmidt/bslint/commit/5eff31f2069cbaec50d48f891390a0734aae1dda

It seems to fix it for me.

**Comment by TwitchBronBron** [comment]
That looks fine to me! Feel free to open a PR with the fix and a unit test verifying the fix, and I'm happy to merge it and cut a release for you!

**Comment by taschmidt** [comment]
Done https://github.com/rokucommunity/bslint/pull/85
